version: '3.8'

services:
  app:
    build: .
    container_name: lichsuviet_app
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=production
      # Sử dụng cơ sở dữ liệu Neon PostgreSQL
      - DATABASE_URL=postgresql://neondb_owner:npg_4lXCGwZWjb3K@ep-misty-pond-a5hdmf9q.us-east-2.aws.neon.tech/neondb?sslmode=require
      # Mật khẩu ngẫu nhiên cho session express
      - SESSION_SECRET=${SESSION_SECRET}

  nginx:
    image: nginx:alpine
    container_name: lichsuviet_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    container_name: lichsuviet_certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
